### ISSUE TITLE
title無法傳入ReactNode問題

### ISSUE THREAD

**Issue by nickychen00** [acrool/acrool-react-table#4]
使用 tableCellMediaSize={400} 時
title 無法傳入 ReactNode

![01](https://github.com/user-attachments/assets/a31dde4b-bf9c-42ff-82f7-0b03a3c0484c)
![02](https://github.com/user-attachments/assets/0357f377-f9fb-4c78-a266-003d34f5c6ef)

**Comment by imagine10255** [comment]
已加上支援 cellMode title 支援 ReactNode

upgrade `@acrool/react-table@5.1.2-alpha.3`

如果有問題再提出 :)
